// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: accountspb/api.proto

package accountspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_accountspb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountspb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_accountspb_api_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_accountspb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accountspb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_accountspb_api_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_accountspb_api_proto protoreflect.FileDescriptor

const file_accountspb_api_proto_rawDesc = "" +
	"\n" +
	"\x14accountspb/api.proto\x12\n" +
	"accountspb\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2d\n" +
	"\x0fAccountsService\x12Q\n" +
	"\fRefreshToken\x12\x1f.accountspb.RefreshTokenRequest\x1a .accountspb.RefreshTokenResponseB\x97\x01\n" +
	"\x0ecom.accountspbB\bApiProtoP\x01Z3github.com/Binit-Dhakal/Foody/accountspb/accountspb\xa2\x02\x03AXX\xaa\x02\n" +
	"Accountspb\xca\x02\n" +
	"Accountspb\xe2\x02\x16Accountspb\\GPBMetadata\xea\x02\n" +
	"Accountspbb\x06proto3"

var (
	file_accountspb_api_proto_rawDescOnce sync.Once
	file_accountspb_api_proto_rawDescData []byte
)

func file_accountspb_api_proto_rawDescGZIP() []byte {
	file_accountspb_api_proto_rawDescOnce.Do(func() {
		file_accountspb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accountspb_api_proto_rawDesc), len(file_accountspb_api_proto_rawDesc)))
	})
	return file_accountspb_api_proto_rawDescData
}

var file_accountspb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_accountspb_api_proto_goTypes = []any{
	(*RefreshTokenRequest)(nil),  // 0: accountspb.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 1: accountspb.RefreshTokenResponse
}
var file_accountspb_api_proto_depIdxs = []int32{
	0, // 0: accountspb.AccountsService.RefreshToken:input_type -> accountspb.RefreshTokenRequest
	1, // 1: accountspb.AccountsService.RefreshToken:output_type -> accountspb.RefreshTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accountspb_api_proto_init() }
func file_accountspb_api_proto_init() {
	if File_accountspb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accountspb_api_proto_rawDesc), len(file_accountspb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accountspb_api_proto_goTypes,
		DependencyIndexes: file_accountspb_api_proto_depIdxs,
		MessageInfos:      file_accountspb_api_proto_msgTypes,
	}.Build()
	File_accountspb_api_proto = out.File
	file_accountspb_api_proto_goTypes = nil
	file_accountspb_api_proto_depIdxs = nil
}
