// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: notificationspb/api.proto

package notificationspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyCustomerRegisteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActivationUrl string                 `protobuf:"bytes,2,opt,name=activation_url,json=activationUrl,proto3" json:"activation_url,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyCustomerRegisteredRequest) Reset() {
	*x = NotifyCustomerRegisteredRequest{}
	mi := &file_notificationspb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyCustomerRegisteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCustomerRegisteredRequest) ProtoMessage() {}

func (x *NotifyCustomerRegisteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCustomerRegisteredRequest.ProtoReflect.Descriptor instead.
func (*NotifyCustomerRegisteredRequest) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyCustomerRegisteredRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyCustomerRegisteredRequest) GetActivationUrl() string {
	if x != nil {
		return x.ActivationUrl
	}
	return ""
}

func (x *NotifyCustomerRegisteredRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NotifyCustomerRegisteredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyCustomerRegisteredResponse) Reset() {
	*x = NotifyCustomerRegisteredResponse{}
	mi := &file_notificationspb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyCustomerRegisteredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCustomerRegisteredResponse) ProtoMessage() {}

func (x *NotifyCustomerRegisteredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCustomerRegisteredResponse.ProtoReflect.Descriptor instead.
func (*NotifyCustomerRegisteredResponse) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{1}
}

type NotifyVendorRegisteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActivationUrl string                 `protobuf:"bytes,2,opt,name=activation_url,json=activationUrl,proto3" json:"activation_url,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyVendorRegisteredRequest) Reset() {
	*x = NotifyVendorRegisteredRequest{}
	mi := &file_notificationspb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyVendorRegisteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyVendorRegisteredRequest) ProtoMessage() {}

func (x *NotifyVendorRegisteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyVendorRegisteredRequest.ProtoReflect.Descriptor instead.
func (*NotifyVendorRegisteredRequest) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyVendorRegisteredRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyVendorRegisteredRequest) GetActivationUrl() string {
	if x != nil {
		return x.ActivationUrl
	}
	return ""
}

func (x *NotifyVendorRegisteredRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NotifyVendorRegisteredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyVendorRegisteredResponse) Reset() {
	*x = NotifyVendorRegisteredResponse{}
	mi := &file_notificationspb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyVendorRegisteredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyVendorRegisteredResponse) ProtoMessage() {}

func (x *NotifyVendorRegisteredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyVendorRegisteredResponse.ProtoReflect.Descriptor instead.
func (*NotifyVendorRegisteredResponse) Descriptor() ([]byte, []int) {
	return file_notificationspb_api_proto_rawDescGZIP(), []int{3}
}

var File_notificationspb_api_proto protoreflect.FileDescriptor

const file_notificationspb_api_proto_rawDesc = "" +
	"\n" +
	"\x19notificationspb/api.proto\x12\x0fnotificationspb\"r\n" +
	"\x1fNotifyCustomerRegisteredRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eactivation_url\x18\x02 \x01(\tR\ractivationUrl\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\"\n" +
	" NotifyCustomerRegisteredResponse\"p\n" +
	"\x1dNotifyVendorRegisteredRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eactivation_url\x18\x02 \x01(\tR\ractivationUrl\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\" \n" +
	"\x1eNotifyVendorRegisteredResponse2\x96\x02\n" +
	"\x13NotificationService\x12\x81\x01\n" +
	"\x18NotifyCustomerRegistered\x120.notificationspb.NotifyCustomerRegisteredRequest\x1a1.notificationspb.NotifyCustomerRegisteredResponse\"\x00\x12{\n" +
	"\x16NotifyVendorRegistered\x12..notificationspb.NotifyVendorRegisteredRequest\x1a/.notificationspb.NotifyVendorRegisteredResponse\"\x00B\xba\x01\n" +
	"\x13com.notificationspbB\bApiProtoP\x01Z=github.com/Binit-Dhakal/Foody/notificationspb/notificationspb\xa2\x02\x03NXX\xaa\x02\x0fNotificationspb\xca\x02\x0fNotificationspb\xe2\x02\x1bNotificationspb\\GPBMetadata\xea\x02\x0fNotificationspbb\x06proto3"

var (
	file_notificationspb_api_proto_rawDescOnce sync.Once
	file_notificationspb_api_proto_rawDescData []byte
)

func file_notificationspb_api_proto_rawDescGZIP() []byte {
	file_notificationspb_api_proto_rawDescOnce.Do(func() {
		file_notificationspb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificationspb_api_proto_rawDesc), len(file_notificationspb_api_proto_rawDesc)))
	})
	return file_notificationspb_api_proto_rawDescData
}

var file_notificationspb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notificationspb_api_proto_goTypes = []any{
	(*NotifyCustomerRegisteredRequest)(nil),  // 0: notificationspb.NotifyCustomerRegisteredRequest
	(*NotifyCustomerRegisteredResponse)(nil), // 1: notificationspb.NotifyCustomerRegisteredResponse
	(*NotifyVendorRegisteredRequest)(nil),    // 2: notificationspb.NotifyVendorRegisteredRequest
	(*NotifyVendorRegisteredResponse)(nil),   // 3: notificationspb.NotifyVendorRegisteredResponse
}
var file_notificationspb_api_proto_depIdxs = []int32{
	0, // 0: notificationspb.NotificationService.NotifyCustomerRegistered:input_type -> notificationspb.NotifyCustomerRegisteredRequest
	2, // 1: notificationspb.NotificationService.NotifyVendorRegistered:input_type -> notificationspb.NotifyVendorRegisteredRequest
	1, // 2: notificationspb.NotificationService.NotifyCustomerRegistered:output_type -> notificationspb.NotifyCustomerRegisteredResponse
	3, // 3: notificationspb.NotificationService.NotifyVendorRegistered:output_type -> notificationspb.NotifyVendorRegisteredResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificationspb_api_proto_init() }
func file_notificationspb_api_proto_init() {
	if File_notificationspb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificationspb_api_proto_rawDesc), len(file_notificationspb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificationspb_api_proto_goTypes,
		DependencyIndexes: file_notificationspb_api_proto_depIdxs,
		MessageInfos:      file_notificationspb_api_proto_msgTypes,
	}.Build()
	File_notificationspb_api_proto = out.File
	file_notificationspb_api_proto_goTypes = nil
	file_notificationspb_api_proto_depIdxs = nil
}
